services:
  client:
    container_name: portfolio_client
    build:
      context: ./client
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - portfolio_network
    
  server:
    container_name: portfolio_server
    build:
      context: ./server
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - NODE_ENV=production
    env_file: .env
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge


